COVIDAnalysis/COVIDAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django_admin/',admin.site.urls),
    path('admin/',include('admins.urls')),
    path('user/',include('users.urls')),
    path('',include('auths.urls')),
]

COVIDAnalysis/auths/urls.py
from django.urls import path
from . import views

app_name="auths"
urlpatterns = [
    path('', views.index,name="index"),
    path('login/', views.login,name="login"),
    path('register/', views.register,name="register"),
    path('reset/', views.reset, name="reset"),
]

COVIDAnalysis/users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
    path('', views.index,name="index"),
    path('reset', views.reset, name="reset"),
    path('wall', views.wall , name="wall"),
]

COVIDAnalysis/users/models.py
from django.db import models

# Create your models here.

COVIDAnalysis/users/views.py
from django.shortcuts import render,redirect
from auths.models import Authentications,States
from plotly.offline import plot
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import prophet
from prophet.plot import plot_plotly
# Create your views here.

def index(request):
    if 'user_id' in request.session:
        return redirect('/user/wall')
    else:
        return render(request, '/')

def wall(request):
    if 'user_id' not in request.session:
        return redirect('/')
    else:
        user_id = request.session['user_id']
        user = Authentications.objects.get(id=user_id)
        stob=user.state
        
        # print(stname)
        stname=stob.state
        st=States.objects.get(state=stname)
        print(st.data)

        #plotting covid data
        # covid_data= States.objects.all()
        if st.data:
            state_data = pd.read_csv(st.data)
            test=round(int(state_data["Tested"].sum())/1000000,2)
            conf=round(int(state_data["Confirmed"].sum())/1000000,2)
            rec=round(int(state_data["Recovered"].sum())/1000000,2)
            death=round(int(state_data["Death"].sum())/1000000,2)
            active=int(state_data.tail(1).Active)
            value=[test, conf, rec, death]
            name=['Tested', 'Confirmed', 'Recovered', 'Death']
            fig_pie = px.pie(names=name, values=value)
            fig=plot(fig_pie,output_type='div')
            # state_data = pd.read_csv('leave/DelhiCovidData.csv')
            date = list(state_data.Date)
            tested = list(state_data.Tested)
            confirmed = list(state_data.Confirmed)
            recovered = list(state_data.Recovered)
            fig1 = px.area(state_data, x="Date", y=["Confirmed", 'Tested'], title = 'Tested Vs Confirmed')
            fig2 = px.area(state_data, x = 'Date', y = ['Death', 'Recovered', 'Confirmed'], title = 'Confirmed, Recovered and Death')
            fig3 = px.area(state_data, x = 'Date', y = ['Active'], title = 'Active Cases')
            fig4 = px.area(state_data, x = 'Date', y = ['Total Vaccinated', 'Second Dose Vaccinated', 'First Dose Vaccinated'], title = 'Vaccination Details')
            fig5 = px.area(state_data, x = 'Date', y = ['Non-Vaccinated'], title = 'Not Vaccinated')
            fig6 = px.area(state_data, x = 'Date', y = ['Female Vaccinated', 'Male Vaccinated', 'Total Vaccinated'], title = 'Vaccination Details')
            fig7 = px.area(state_data, x = 'Date', y = ['Covaxin Doses', 'Covishield Doses'], title = 'No. of Covaxin and Covishield Doses')
            
            
            
            gplot1 = plot(fig1,output_type='div')
            gplot2 = plot(fig2,output_type='div')
            gplot3 = plot(fig3,output_type='div')
            gplot4 = plot(fig4,output_type='div')
            gplot5 = plot(fig5,output_type='div')
            gplot6 = plot(fig6,output_type='div')
            gplot7 = plot(fig7,output_type='div')
        

            dfn = state_data.iloc[: , [1,5]]
            dfn = dfn.rename(columns={'Date': 'ds', 'Death': 'y'})
            cd_prophet = prophet.Prophet(changepoint_prior_scale=0.15)
            cd_prophet.fit(dfn)
            cd_forecast = cd_prophet.make_future_dataframe(periods=61, freq='D')
            # Make predictions
            cd_forecast = cd_prophet.predict(cd_forecast)
            fig10 = plot_plotly(cd_prophet, cd_forecast).update_layout(xaxis_title="Date", yaxis_title="Death Count",title="Fatality Prediction")
            gplot10 = plot(fig10,output_type='div')

            dfa = state_data.iloc[: , [1,6]]
            dfa = dfa.rename(columns={'Date': 'ds', 'Active': 'y'})
            cda_prophet = prophet.Prophet(changepoint_prior_scale=0.15)
            cda_prophet.fit(dfa)
            cda_forecast = cda_prophet.make_future_dataframe(periods=15, freq='D')
            # Make predictions
            cda_forecast = cda_prophet.predict(cda_forecast)
            fig11 = plot_plotly(cda_prophet, cda_forecast).update_layout(xaxis_title="Date", yaxis_title="Active cases",title="Active Cases Prediction")
            gplot11 = plot(fig11,output_type='div')

            dfc = state_data.iloc[: , [1,3]]
            dfc = dfc.rename(columns={'Date': 'ds', 'Confirmed': 'y'})
            cdc_prophet = prophet.Prophet(changepoint_prior_scale=0.15)
            cdc_prophet.fit(dfc)
            cdc_forecast = cdc_prophet.make_future_dataframe(periods=61, freq='D')
            # Make predictions
            cdc_forecast = cdc_prophet.predict(cdc_forecast)
            fig12 = plot_plotly(cdc_prophet, cdc_forecast).update_layout(xaxis_title="Date", yaxis_title="Confirmed cases",title="Confirmed Cases Prediction")
            gplot12 = plot(fig12,output_type='div')
            context = {
                'Tested':test,
                'Confirmed':conf,
                'Recovered':rec,
                'Death':death,
                'Active':active,
                'st':st,
                "plot_div1":gplot1,
                "plot_div2":gplot2,
                "plot_div3":gplot3,
                "plot_div4":gplot4,
                "plot_div5":gplot5,
                "plot_div6":gplot6,
                "plot_div7":gplot7,
                "plot_div10":gplot10,
                "plot_div11":gplot11,
                "plot_div12":gplot12,
                "plot_div":fig,
            }
            return render(request, 'users/userpage.html',context)
        else:
            data_error="State data hasnt been uploaded"
            context={
                'data_error':data_error,
                'st':st,
            }
            return render(request, 'users/userpage.html',context)

def reset(request):
    if 'user_id' not in request.session:
        return redirect('/')
    else:
        request.session.clear()
        print("session has been cleared")
        return redirect("/")

COVIDAnalysis/templates/users/userpage.html
{% load static %}
<!-- <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>Users Page</title>
</head>

<body>

    <a href="{% url 'users:reset' %}" style="color:#3498db;">Sign Out</a>
</body>
  
</html> -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'users/css/dashboard.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.2/css/fontawesome.min.css"
        integrity="sha384-X8QTME3FCg1DLb58++lPvsjbQoCT9bp3MsUU3grbIny/3ZwUJkRNO8NPW6zqzuW9" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="analytics-outline"></ion-icon>
                        </span>
                        <span class="title">Co-Analysis</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'users:wall' %}">
                        <span class="icon">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'users:reset' %}">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Sign out</span>
                    </a>
                </li>
            </ul>
        </div>

        <!--main-->
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <ion-icon name="menu-outline"></ion-icon>
                </div>
                <!--search-->
                <div class="search">
                    <label>
                        <input type="text" placeholder="Search Here">
                        <ion-icon name="search-outline"></ion-icon>
                    </label>
                </div>
                <!--UserImg-->
                <div class="user">
                    <ion-icon name="person-circle-outline"></ion-icon>
                </div>
            </div>

            <!--cards-->

            <div class="cardbox">
                <div class="card">
                    <div>
                        <div class="number">{{Tested}} M</div>
                        <div class="cardName">Tested</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="medkit-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="number">{{Confirmed}} M</div>
                        <div class="cardName">Confirmed</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="swap-vertical-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="number">{{Recovered}} M</div>
                        <div class="cardName">Recovered</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="fitness-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="number">{{Death}} M</div>
                        <div class="cardName">Death</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="heart-dislike-circle-outline"></ion-icon>
                    </div>
                </div>
            </div>

            <!--Approval-->
            <div class="details">
                {% if data_error %}
                <div class="recentapproval">
                    <div class="cardheader">
                        <h2>{{ data_error }}</h2>
                    </div>
                </div>
                {% else %}
                <div class="recentapproval">
                    <div class="cardheader">
                        <h2>{{st.state}}</h2>
                        <h2>Active Cases: {{Active}}</h2>
                    </div>
                    {% if Active > 100000 %}
                    <div class="cardheader">
                        <marquee direction="left">
                            <h2 style="color: red;"> Red Zone Area (COVID Hotspot). Lockdown imposed 24*7. Use Proper
                                precautions. Maintain Social Distancing and use masks.</h2>
                        </marquee>
                        
                    </div>
                    {% else %}
                    {% if Active > 50000 %}
                    <div class="cardheader">
                        <marquee direction="Left">
                            <h2 style="color: rgb(249, 138, 47);"> Orange Zone Area. Lockdown is imposed for public. Only
                                authorized person can go out. Use Proper precautions. Maintain Social Distancing and use
                                masks.</h2>
                        </marquee>
                        
                    </div>
                    {% else %}
                    {% if Active > 25000 %}
                    <div class="cardheader">
                        <marquee direction="left">
                            <h2 style="color: rgb(255, 251, 1);"> Yellow Zone Area. Lockdown is imposed at nights. Use
                                Proper precautions. Maintain Social Distancing and use masks.</h2>
                        </marquee>
                        
                    </div>
                    {%else%}
                    <div class="cardheader">
                        <marquee direction="left">
                            <h2 style="color: rgb(0, 255, 42); font-weight: lighter;"> Green Zone area. Use proper precautions. Maintain social
                                distancing and use masks.</h2>
                        </marquee>
                        
                    </div>
                    {% endif %}
                    {% endif %}
                    {% endif %}
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div1}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div2}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div3}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div4}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div5}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div6}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div7}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div10}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div11}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div12}}
                        {% endautoescape %}
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>


    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    <script>
        // Menu Toggle
        let toggle = document.querySelector('.toggle');
        let navigation = document.querySelector('.navigation');
        let main = document.querySelector('.main');

        toggle.onclick = function () {
            navigation.classList.toggle('active');
            main.classList.toggle('active');

        }

        //add hovered class in selected list item 
        let list = document.querySelectorAll('.navigation li');
        function activelink() {
            list.forEach((item) =>
                item.classList.remove('hovered'));
            this.classList.add('hovered');
        }
        list.forEach((item) =>
            item.addEventListener('mouseover', activelink)
        )
    </script>
</body>

</html>