COVIDAnalysis/COVIDAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django_admin/',admin.site.urls),
    path('admin/',include('admins.urls')),
    path('user/',include('users.urls')),
    path('',include('auths.urls')),
]

COVIDAnalysis/auths/urls.py
from django.urls import path
from . import views

app_name="auths"
urlpatterns = [
    path('', views.index,name="index"),
    path('login/', views.login,name="login"),
    path('register/', views.register,name="register"),
    path('reset/', views.reset, name="reset"),
]

COVIDAnalysis/auths/models.py
import email, re
from django.db import models
from django.contrib.auth.hashers import make_password, check_password
import datetime
import os

# Create your models here.

class UserManager(models.Manager):

    def register_validator(self, postData):
        errors = {}
        # Validation Rules for First Name
        if len(postData['name']) < 1:
            errors["name"] = "Username is required"
        elif len(postData['email']) < 1:
            errors["email"] = "Email is required"
        elif len(postData['state']) < 1:
            errors["state"] = "State is required"
        # Validation Rules for Password
        elif len(postData['password']) < 1:
            errors["password"] = "Password is required"
        elif not re.search(r"^[A-Za-z0-9_!#$%&'*+\/=?`{|}~^.-]+@[A-Za-z0-9.-]+$", postData['email']):
            errors["email"] = "Email should be in correct format"
        elif not re.findall('\d', postData['password']):
            errors["password"] = "Password must contain at least 1 number"
        elif not re.findall('[A-Z]', postData['password']):
            errors["password"] = "Password must contain at least 1 uppercase letter"
        elif not re.findall('[a-z]', postData['password']):
            errors["password"] = "Password must contain at least 1 lowercase letter"   
        elif not re.findall('[!@#&*_]', postData['password']):
            errors["password"] = "Password must contain at least 1 symbol [!@#&*_]"
        elif len(postData['password']) < 8:
            errors["password"] = "Password should be at least 8 characters"
        elif postData['email'] in list(Authentications.objects.values_list('email', flat=True)):
            errors["email"] = "Email is already registered"
        

        # Validation Rules for Confirm Password
        elif postData['password'] != postData['confirm_password']:
            errors["confirm_password"] = "Password and Password Confirmation did not match"

        return errors

    def login_validator(self, postData):
        errors = {}
        # Validation Rules for Login Email
        if len(postData['email']) < 1:
            errors["email"] = "Username is required"

        # Validation Rules for Login Password
        elif len(postData['password']) < 1:
            errors["password"] = "Password is required"
            
        elif postData['email'] not in list(Authentications.objects.values_list('email', flat=True)):
            errors["email"] = "User does not exists"
        else:
            auth = Authentications.objects.get(email=postData['email'])
            
            check_pw = check_password(postData['password'], auth.password)

            if  not check_pw:
                errors["password"] = "Password is not correct"
            elif auth.isApproved == False:
                errors['email'] = "Admin hasnt approved your profile"
            

        return errors

def filepath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('covid_data/', filename)

class States(models.Model):
    state_id = models.IntegerField()
    state = models.CharField(primary_key=True ,max_length=50)
    data = models.FileField(upload_to=filepath,null=True)

    def __str__(self):
        return self.state

class Authentications(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=16)
    isApproved = models.BooleanField(default=False)
    isAdmin = models.BooleanField(default=False)
    state= models.ForeignKey(States,db_column='state', on_delete=models.CASCADE,null=True) 

    objects = UserManager()

    def __str__(self):
        return self.email

COVIDAnalysis/auths/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from .models import Authentications, States
from templates import *
from django.contrib.auth.hashers import make_password, check_password
from django.core import mail
# Create your views here.

def index(request):
    if 'isAdmin' in request.session:
        if request.session['isAdmin']==True:
            return redirect('/admin/wall')
        else:
            return redirect('/user/wall')
    else:
        return redirect('/login')

def register(request):
    state_list = States.objects.values()
    context = {
        'state_list': state_list,
    }
    if request.method == "POST":
        errors = Authentications.objects.register_validator(request.POST)
        if len(errors):
            for key, value in errors.items():
                messages.add_message(
                    request, messages.ERROR, value, extra_tags='register')
            return render(request, 'auths/register.html',context)
        else:
            state_id = States.objects.get(state=request.POST['state'])

            hash_pw=make_password(request.POST['password'])
            print(hash_pw)
            auth = Authentications.objects.create(
            name=request.POST['name'], email=request.POST['email'], password=hash_pw, state=state_id)
            errors["email"] = "Account is created"
            for key, value in errors.items():
                messages.add_message(
                    request, messages.ERROR, value, extra_tags='register')
            request.session['user_id'] = auth.id
            #sending mail to admin
            # acc_name = request.POST['name']
            # acc_state = request.POST['state']
            # acc_email = "tarun78ak@gmail.com"
            # try:
            #     print("mail sent")
            
            #     connection = mail.get_connection()
            #     connection.open()

            #     email1 = mail.EmailMessage(
            #     'User Request',
            #     '''Dear Admin 
            #         A new user '{}' has sent request for state the '{}'. Kindly look into it.

            #         Thank you.'''.format(acc_name, acc_state),
            #     'proton01sam@proton.me',
            #     [acc_email],
            #     connection=connection,
            #     )
            #     email1.send() # Send the email

                # return render(request, 'auths/register.html',context)
            # except:
            #     print("connection error")
            #     return render(request, 'auths/register.html',context)
    else:
        return render(request, 'auths/register.html',context)

def login(request):
    if request.method == "POST":
        print(request.POST)
        errors = Authentications.objects.login_validator(request.POST)
        if len(errors):
            for key, value in errors.items():
                messages.add_message(
                    request, messages.ERROR, value, extra_tags='login')
            return redirect('/')
        else:
            auth = Authentications.objects.get(email=request.POST['email'])
            request.session['user_id'] = auth.id
            request.session['isAdmin'] = auth.isAdmin

            if request.session['isAdmin']==True:
                return redirect('/admin/wall')
            else:
                return redirect('/user/wall')
    else:
        return render(request, 'auths/login.html')

def reset(request):
    if 'user_id' not in request.session:
        return redirect('/')
    else:
        request.session.clear()
        print("session has been cleared")
        return redirect("/")

COVIDAnalysis/templates/auths/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log in</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="{% static 'auths/login_stylee.css' %}">
</head>
<body>
    <div class="main">
        <main>
            
            <section class="flex info">
                <h1>Welcome to 
                    <span>
                        <div class="waviy animate__animated animate__backInDown">
                            <span style="--i:1">C</span>
                            <span style="--i:1">o</span>
                            <span style="--i:1">v</span>
                            <span style="--i:1">i</span>
                            <span style="--i:1">d</span>
                            <span style="--i:1"> </span>
                            <span style="--i:1">A</span>
                            <span style="--i:1">n</span>
                            <span style="--i:1">a</span>
                            <span style="--i:1">l</span>
                            <span style="--i:1">y</span>
                            <span style="--i:1">s</span>
                            <span style="--i:1">i</span>
                            <span style="--i:1">s</span>
                        </div>
                    </span>
                    System...</h1>
            </section>

            <section style="overflow-x:hidden" class="flex form-section flex-column">
                <h1 class="form-header animate__animated animate__bounceInRight">Log in</h1>
                <form id="form" action="{% url 'auths:login' %}" method="post" class="form">
                    {% csrf_token %}
                    <div class="username">
                        <!-- <label for="email">Username</label> -->
                        <input type="text" name="email" placeholder="Enter username" class="form-input animate__animated animate__bounceInLeft" required />
                        <!-- <input type="text" placeholder="Enter Username" class="form-input"> -->
                    </div>
                    <div class="password">
                        <!-- <label for="password">Password</label> -->
                <input type="password" name="password" placeholder="Enter password" class="form-password animate__animated animate__bounceInRight" required />
                        <!-- <input type="password" placeholder="Enter Password" class="form-password"> -->
                    </div>
                    <div  class="error-password">

                        {% if messages %}
                        {% for message in messages %}
                        {% if "login" in message.tags %}
                        <span class="error-password">{{ message }}</span>
                        <br>
                        <br>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="enter">
                        <!-- <button type="submit" class="btn btn-login animate__animated animate__shakeX"><a href="{% url 'auths:login' %}">Log in</a></button> -->
                        <a href="{% url 'auths:login' %}"><button type="submit"
                            class="btn btn-login animate__animated animate__bounceInLeft">Login</button></a>
                        <div class="divider animate__animated animate__bounceInRight">Don't have an account?</div>
                        <a href="{% url 'auths:register' %}"><button type="button"
                            class="btn btn-register animate__animated animate__bounceInLeft">Register</button></a>
                    </div>
                </form>
    
            </section>
        </main>
    </div>
    
</body>
</html>

COVIDAnalysis/templates/auths/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="{% static 'auths/register_stylee.css' %}">
</head>
<body>
    <div class="main">
        <main>
            
            <section class="flex info">
                <h1>Welcome to 
                    <span>
                        <div class="waviy animate__animated animate__backInDown">
                            <span style="--i:1">C</span>
                            <span style="--i:1">o</span>
                            <span style="--i:1">v</span>
                            <span style="--i:1">i</span>
                            <span style="--i:1">d</span>
                            <span style="--i:1"> </span>
                            <span style="--i:1">A</span>
                            <span style="--i:1">n</span>
                            <span style="--i:1">a</span>
                            <span style="--i:1">l</span>
                            <span style="--i:1">y</span>
                            <span style="--i:1">s</span>
                            <span style="--i:1">i</span>
                            <span style="--i:1">s</span>
                        </div>
                    </span>
                    System...</h1>
            </section>

            <section style="overlow-x:hidden" class="flex form-section flex-column">
                <h1 class="form-header animate__animated animate__bounceInRight">Register here</h1>
                <form id="form"action="{% url 'auths:register' %}" method="post" class="form">
                    {% csrf_token %}
                    <div class="username">
                        <!-- <label for="name">Name</label> -->
                        <input type="text" name="name" placeholder="Enter Name" class="form-input animate__animated animate__bounceInLeft" required />
                        <!-- <input type="text" placeholder="Enter Username" class="form-input" required> -->
                    </div>
                    <div class="email">
                        <!-- <label for="email">Email</label> -->
                        <input type="text" name="email" placeholder="Enter Email" class="form-input animate__animated animate__bounceInRight" required />
                        <!-- <input type="email" placeholder="Enter Email" class="form-input" required> -->
                    </div>
                    <div class="state">
                        <!-- <label for="state">State</label> -->
                        <select name="state" id="state" class="select-state animate__animated animate__bounceInLeft"required>
                            <option value="" disabled selected hidden>Please select a State</option>
                            {% for entry in state_list %}
                            {% if entry.state != "India" %}
                            <option>{{entry.state}}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                        <!-- <select name="cars" class="select-state" required>
                            <option value="" disabled selected hidden>Select State</option>
                            <option value="delhi">Delhi</option>
                            <option value="wb">West Bengal</option>
                            <option value="up">Uttar Pradesh</option>
                            <option value="tn">Tamin Nadu</option>
                            <option value="tl">Telangana</option>
                        </select> -->
                    </div>
                    
                    <div class="password">
                        <!-- <label for="password">Password</label> -->
                        <input type="password" name="password" placeholder="Enter Password" class="form-input animate__animated animate__bounceInRight" required />
                        <!-- <input type="password" placeholder="Enter Password" class="form-input" required> -->
                    </div>
                    <div class="con-password">
                        <!-- <label for="confirm_password">Confirm Password</label> -->
                        <input type="password" name="confirm_password" placeholder="Enter Confirm password" class="form-input animate__animated animate__bounceInLeft"required />
                        <!-- <input type="password" placeholder="Confirm Password" class="form-input" required> -->
                    </div>
                    <div class="error-password">

                        {% if messages %}
                        {% for message in messages %}
                        {% if "register" in message.tags %}
                        <span class="error-password">{{ message }}</span>
                        <br>
                        <br>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="enter">
                        <a href="{% url 'auths:register' %}"><button type="submit"
                            class="btn btn-register animate__animated animate__bounceInRight">Create Account</button></a>
                        <div class="divider animate__animated animate__bounceInLeft">Already have an account?</div>
                        <a href="{% url 'auths:login' %}"><button type="button"
                            class="btn btn-login animate__animated animate__bounceInRight">Login</button></a>
                        
                    </div>
                </form>
    
            </section>
        </main>
    </div>
    
</body>
</html>