COVIDAnalysis/COVIDAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django_admin/',admin.site.urls),
    path('admin/',include('admins.urls')),
    path('user/',include('users.urls')),
    path('',include('auths.urls')),
]

COVIDAnalysis/admins/urls.py
from django.urls import path
from . import views

app_name="admins"
urlpatterns = [
    path('', views.index,name="index"),
    path('reset', views.reset, name="reset"),
    path('wall', views.wall , name="wall"),
    path('accepted/',views.accept_request, name='accept_request'),
    path('approvalpage', views.approvalpage, name="approvalpage"),
    path('state/<state>', views.state, name="state"),
    path('uploaddata', views.uploaddata, name="uploaddata"),
    path('accepted/',views.accept_request, name='accept_request'),
    path('declined/',views.decline_request, name='decline_request'),
]

COVIDAnalysis/auths/urls.py
from django.urls import path
from . import views

app_name="auths"
urlpatterns = [
    path('', views.index,name="index"),
    path('login/', views.login,name="login"),
    path('register/', views.register,name="register"),
    path('reset/', views.reset, name="reset"),
]

COVIDAnalysis/templates/admins/adminpage.html
{% load static %}
<!-- <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>Admin Page</title>
</head>

<body>

    <a href="{% url 'admins:approvalpage' %}" style="color:#3498db;">Approval Page</a><br>
    <a href="{% url 'admins:reset' %}" style="color:#3498db;">Sign Out</a>
</body>
  
</html> -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'admins/css/dashboard.css' %}" type="text/css">
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.2/css/fontawesome.min.css"
        integrity="sha384-X8QTME3FCg1DLb58++lPvsjbQoCT9bp3MsUU3grbIny/3ZwUJkRNO8NPW6zqzuW9" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="analytics-outline"></ion-icon>
                        </span>
                        <span class="title">Co-Analysis</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:wall' %}">
                        <span class="icon">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:wall' %}">
                        <span class="icon">
                            <ion-icon name="location-outline"></ion-icon>
                        </span>
                        <span class="title">All State</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:approvalpage' %}">
                        <span class="icon">
                            <ion-icon name="checkmark-done-circle-outline"></ion-icon>
                        </span>
                        <span class="title">User Approval</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:uploaddata' %}">
                        <span class="icon">
                            <ion-icon name="cloud-upload-outline"></ion-icon>
                        </span>
                        <span class="title">Upload Data</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:reset' %}">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Sign out</span>
                    </a>
                </li>
            </ul>
        </div>

        <!--main-->
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <ion-icon name="menu-outline"></ion-icon>
                </div>
                <!--search-->
                <!-- <div class="search">
                    <label>
                        <input type="text" placeholder="Search Here">
                        <ion-icon name="search-outline"></ion-icon>
                    </label>
                </div> -->

                <!--DropDown-->
                <div class="dropdown" id="drop-down">
                    <span>State Wise Analysis</span>
                    <label>
                        <input type="checkbox">
                        <ul>
                            {% for entry in state_list %}
                            {% if entry.state != "India" %}
                            <a href="{% url 'admins:state' entry.state %}" style="text-decoration: none;">
                                <li>{{entry.state}}</li>
                            </a>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </label>
                </div>
                <!--UserImg-->
                <div class="user">
                    <ion-icon name="person-circle-outline"></ion-icon>
                </div>
            </div>

            <!--cards-->
            <div class="cardbox">
                <div class="card">
                    <div>
                        <div class="number">{{Tested}} M</div>
                        <div class="cardName">Tested</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="medkit-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="number">{{Confirmed}} M</div>
                        <div class="cardName">Confirmed</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="swap-vertical-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="number">{{Recovered}} M</div>
                        <div class="cardName">Recovered</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="fitness-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="number">{{Death}} M</div>
                        <div class="cardName">Death</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="heart-dislike-circle-outline"></ion-icon>
                    </div>
                </div>
            </div>

            <!--Approval-->
            <div class="details">
                {% if data_error %}
                <div class="recentapproval">
                    <div class="cardheader">
                        <h2>{{ data_error }}</h2>
                    </div>
                </div>
                {% else %}
                <div class="recentapproval">
                    <div class="cardheader">
                        <h2>{{st.state}} (5 states)</h2>
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div1}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div2}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div3}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div4}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div5}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div6}}
                        {% endautoescape %}
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    <script>
        // Menu Toggle
        let toggle = document.querySelector('.toggle');
        let navigation = document.querySelector('.navigation');
        let main = document.querySelector('.main');

        toggle.onclick = function () {
            navigation.classList.toggle('active');
            main.classList.toggle('active');

        }

        //add hovered class in selected list item 
        let list = document.querySelectorAll('.navigation li');
        function activelink() {
            list.forEach((item) =>
                item.classList.remove('hovered'));
            this.classList.add('hovered');
        }
        list.forEach((item) =>
            item.addEventListener('mouseover', activelink)
        )

        //dropdown
        $(document).ready(function () {
            $('.dropdown ul>li').click(function () {
                $('.dropdown ul>li').each(function () {
                    $(this).removeClass('drop-selected');
                });
                $(this).toggleClass('drop-selected');
                $('.dropdown>span').text($(this).attr("val"))
            });
        });
    </script>
</body>

</html>

COVIDAnalysis/templates/admins/approvalpage.html
{% load static %}
<!-- <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>Approval Page</title>
</head>

<body>
  <div>
      <div>
        <table>
          <thead id="head">
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>State</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for r in table_rows %}
            <tr>
  
              <td>{{r.name}}</td>
              <td>{{r.email}}</td>
              <td>{{r.state}}</td>
  
  
              <td class="Action">
                <form action="{% url 'admins:accept_request' %}" method="get">
                    <input type="hidden" name="id" value="{{r.id}}" id="inputButton">
                  <button type="submit" class="btn btn-link btn-sm btn-rounded" id="accept">Accept
                  </button>
                </form>
                <br>
                <form action="{% url 'admins:decline_request' %}" method="get">
                  <input type="hidden" name="id" value="{{r.id}}" id="inputButton">
                <button type="submit" class="btn btn-link btn-sm btn-rounded" id="decline">Decline
                </button>
              </form>
              </td>
  
            </tr>
            {% endfor %}
  
  
  
  
  
        </table>
      </div>
    </div>
    <a href="{% url 'admins:wall' %}" style="color:#3498db;">Admin Dashboard</a><br>
    <a href="{% url 'admins:reset' %}" style="color:#3498db;">Sign Out</a>
</body>
  
</html> -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'admins/css/dashboard.css' %}" type="text/css">

</head>

<body>
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="analytics-outline"></ion-icon>
                        </span>
                        <span class="title">Co-Analysis</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:wall' %}">
                        <span class="icon">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>
                <li>
                  <a href="#">
                      <span class="icon">
                          <ion-icon name="location-outline"></ion-icon>
                      </span>
                      <span class="title">All State</span>
                  </a>
                </li>
                <li>
                    <a href="{% url 'admins:approvalpage' %}">
                        <span class="icon">
                            <ion-icon name="checkmark-done-circle-outline"></ion-icon>
                        </span>
                        <span class="title">User Approval</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:uploaddata' %}">
                        <span class="icon">
                            <ion-icon name="cloud-upload-outline"></ion-icon>
                        </span>
                        <span class="title">Upload Data</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:reset' %}">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Sign out</span>
                    </a>
                </li>
            </ul>
        </div>

        <!--main-->
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <ion-icon name="menu-outline"></ion-icon>
                </div>
                <!--search-->
                <div class="search">
                    <label>
                        <input type="text" placeholder="Search Here">
                        <ion-icon name="search-outline"></ion-icon>
                    </label>
                </div>
                
                <!--Dropdown-->


                <!--UserImg-->
                <div class="user">
                    <ion-icon name="person-circle-outline"></ion-icon>
                </div>
            </div>

                <!--Approval-->
            <div class="details">
                <div class="recentapproval">
                    <div class="cardheader">
                        <h2>Recent Approvals</h2>
                    </div>
                    <!-- <table>
                        <thead>
                        <tr>
                            <td>Name</td>
                            <td>Email</td>
                            <td>State</td>
                            <td>Accept</td>
                            <td>Delete</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Saurabh Singh</td>
                            <td>Saurabh@gmail.com</td>
                            <td>UP</td>
                            <td ><a href="#" style="text-decoration: none; color: #fff;"><button class="btn1">Accept</button></a></td>
                            <td ><a href="#" style="text-decoration: none; color: #fff;"><button class="btn1">Delete</button></a></td>
                        </tr>
                    </tbody>
                    </table> -->
                    <table>
                      <thead id="head">
                        <tr>
                          <th>Name</th>
                          <th>Email</th>
                          <th>State</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for r in table_rows %}
                        <tr>
              
                          <td>{{r.name}}</td>
                          <td>{{r.email}}</td>
                          <td>{{r.state}}</td>
              
              
                          <td class="Action">
                            <form action="{% url 'admins:accept_request' %}" method="get">
                                <input type="hidden" name="id" value="{{r.id}}" id="inputButton">
                              <button type="submit" class="btn1" id="accept">Accept
                              </button>
                            </form>
                            <br>
                            <form action="{% url 'admins:decline_request' %}" method="get">
                              <input type="hidden" name="id" value="{{r.id}}" id="inputButton">
                            <button type="submit" class="btn1" id="decline">Decline
                            </button>
                          </form>
                          </td>
              
                        </tr>
                        {% endfor %}
              
              
              
              
              
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    
    <script>
        // Menu Toggle
        let toggle = document.querySelector('.toggle');
        let navigation = document.querySelector('.navigation');
        let main = document.querySelector('.main');

        toggle.onclick = function () {
            navigation.classList.toggle('active');
            main.classList.toggle('active');

        }

        //add hovered class in selected list item 
        let list = document.querySelectorAll('.navigation li');
        function activelink() {
            list.forEach((item) =>
                item.classList.remove('hovered'));
            this.classList.add('hovered');
        }
        list.forEach((item) =>
            item.addEventListener('mouseover', activelink)
        )

        // Dropdown

    </script>
</body>

</html>

COVIDAnalysis/templates/admins/state.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'admins/css/dashboard.css' %}" type="text/css">
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.2/css/fontawesome.min.css"
        integrity="sha384-X8QTME3FCg1DLb58++lPvsjbQoCT9bp3MsUU3grbIny/3ZwUJkRNO8NPW6zqzuW9" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="analytics-outline"></ion-icon>
                        </span>
                        <span class="title">Co-Analysis</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:wall' %}">
                        <span class="icon">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="location-outline"></ion-icon>
                        </span>
                        <span class="title">{{st.state}}</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:approvalpage' %}">
                        <span class="icon">
                            <ion-icon name="checkmark-done-circle-outline"></ion-icon>
                        </span>
                        <span class="title">User Approval</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:uploaddata' %}">
                        <span class="icon">
                            <ion-icon name="cloud-upload-outline"></ion-icon>
                        </span>
                        <span class="title">Upload Data</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admins:reset' %}">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Sign out</span>
                    </a>
                </li>
            </ul>
        </div>
        <!--main-->
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <ion-icon name="menu-outline"></ion-icon>
                </div>
                <!--search-->
                <div class="search">
                    <label>
                        <input type="text" placeholder="Search Here">
                        <ion-icon name="search-outline"></ion-icon>
                    </label>
                </div>
                <!--UserImg-->
                <div class="user">
                    <ion-icon name="person-circle-outline"></ion-icon>
                </div>
            </div>

            <!--cards-->
            <div class="cardbox">
                <div class="card">
                    <div>
                        <div class="number">{{Tested}} M</div>
                        <div class="cardName">Tested</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="medkit-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="number">{{Confirmed}} M</div>
                        <div class="cardName">Confirmed</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="swap-vertical-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="number">{{Recovered}} M</div>
                        <div class="cardName">Recovered</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="fitness-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="number">{{Death}} M</div>
                        <div class="cardName">Death</div>
                    </div>
                    <div class="iconbox">
                        <ion-icon name="heart-dislike-circle-outline"></ion-icon>
                    </div>
                </div>
            </div>

            <!--Approval-->
            <div class="details">
                {% if data_error %}
                <div class="recentapproval">
                    <div class="cardheader">
                        <h2>{{ data_error }}</h2>
                    </div>
                </div>
                {% else %}
                <div class="recentapproval">
                    <div class="cardheader">
                        <h2>{{st.state}}</h2>
                        <h2>Active Cases: {{Active}}</h2>
                    </div>
                    {% if Active > 100000 %}
                    <div class="cardheader">
                        <marquee direction="left">
                            <h2 style="color: red;"> Red Zone Area (COVID Hotspot). Lockdown imposed 24*7. Use Proper
                                precautions. Maintain Social Distancing and use masks.</h2>
                        </marquee>
                        
                    </div>
                    {% else %}
                    {% if Active > 50000 %}
                    <div class="cardheader">
                        <marquee direction="Left">
                            <h2 style="color: rgb(249, 138, 47);"> Orange Zone Area. Lockdown is imposed for public. Only
                                authorized person can go out. Use Proper precautions. Maintain Social Distancing and use
                                masks.</h2>
                        </marquee>
                        
                    </div>
                    {% else %}
                    {% if Active > 25000 %}
                    <div class="cardheader">
                        <marquee direction="left">
                            <h2 style="color: rgb(255, 251, 1);"> Yellow Zone Area. Lockdown is imposed at nights. Use
                                Proper precautions. Maintain Social Distancing and use masks.</h2>
                        </marquee>
                        
                    </div>
                    {%else%}
                    <div class="cardheader">
                        <marquee direction="left">
                            <h2 style="color: rgb(0, 255, 42);"> Green Zone Area. Use Proper precautions. Maintain Social
                                Distancing and use masks.</h2>
                        </marquee>
                        
                    </div>
                    {% endif %}
                    {% endif %}
                    {% endif %}
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div1}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div2}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div3}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div4}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div5}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div6}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div7}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div10}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div11}}
                        {% endautoescape %}
                    </div>
                </div>
                <div class="recentapproval">
                    <div class="cardheader">
                        {% autoescape off %}
                        {{plot_div12}}
                        {% endautoescape %}
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    <script>
        // Menu Toggle
        let toggle = document.querySelector('.toggle');
        let navigation = document.querySelector('.navigation');
        let main = document.querySelector('.main');

        toggle.onclick = function () {
            navigation.classList.toggle('active');
            main.classList.toggle('active');

        }

        //add hovered class in selected list item 
        let list = document.querySelectorAll('.navigation li');
        function activelink() {
            list.forEach((item) =>
                item.classList.remove('hovered'));
            this.classList.add('hovered');
        }
        list.forEach((item) =>
            item.addEventListener('mouseover', activelink)
        )
    </script>
</body>

</html>